
  web:
    restart: always
    build: ./webOfficina
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./webOfficina:/usr/src/app
      - ./webOfficina/static:/usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn webOfficina.wsgi:application -w 2 -b :8000 --reload

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"

  data:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"
