# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'Nome')),
                ('surname', models.CharField(max_length=30, verbose_name=b'Cognome')),
                ('nickname', models.CharField(max_length=30, verbose_name=b'Nominativo')),
            ],
            options={
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id_mechanic', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name=b'Nome')),
                ('surname', models.CharField(max_length=30, verbose_name=b'Cognome')),
            ],
            options={
                'verbose_name_plural': 'Meccanici',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(verbose_name=b'Data di prenotazione')),
                ('hour_start_reservation', models.TimeField()),
                ('hour_end_reservation', models.TimeField()),
                ('use', models.CharField(choices=[(b'c', b'Comunitario'), (b'm', b'Medico'), (b'p', b'Personali')], max_length=15, verbose_name=b'Uso')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfficina.Client', verbose_name=b'Cliente')),
                ('id_mechanic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appOfficina.Mechanic')),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('targa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Veicoli',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfficina.Vehicle', verbose_name=b'Veicolo'),
        ),
    ]
